---
- name: Enable RT repo
  community.general.rhsm_repository:
    name: rhel-9-for-x86_64-rt-rpms
    state: enabled

- name: Enable NFV repo
  community.general.rhsm_repository:
    name: rhel-9-for-x86_64-nfv-rpms
    state: enabled

- name: Install Kernel RT
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - kernel-rt
    - kernel-rt-kvm
    - tuned-profiles-nfv-host
    - realtime-tests

- name: Set default kernel as RT
  ansible.builtin.shell: grubby --set-default-index 0