---
- name: Create station bridge
  community.general.nmcli:
    conn_name: station-bus
    state: present
    type: bridge
    ifname: station-nic
    ip4:
      - "{{ vpac_network.ip4 }}"
    gw4: "{{ vpac_network.gw4 }}"
    dns4: "{{ vpac_network.dns4 }}"
    autoconnect: true

- name: Create station bridge nic
  community.general.nmcli:
    conn_name: station-ext
    state: present
    type: ethernet
    slave_type: bridge
    master: station-nic
    ifname: "{{ vpac_network.station_nic }}"
    autoconnect: true

- name: Bring down physical nic
  community.general.nmcli:
    conn_name: "{{ vpac_network.station_nic }}"
    autoconnect: false