---
- name: Setup tuned
  ansible.builtin.include_role:
    name: linux-system-roles.tuned

- name: Setup isolated cores
  ansible.builtin.template:
    src: realtime-variables.conf.j2
    dest: /etc/tuned/realtime-variables.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Disable irqbalance
  ansible.builtin.service:
    name: irqbalance
    enabled: false
    state: stopped
