---
- name: Install helpful packages
  ansible.builtin.package:
    name: tuned
    state: present

- name: Enable tuned service
  ansible.builtin.service:
    name: tuned
    enabled: true
    state: started

- name: Setup isolated cores
  ansible.builtin.template:
    src: realtime-variables.conf.j2
    dest: /etc/tuned/realtime-variables.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
