---
- name: Install helpful packages
  ansible.builtin.package: name={{ item }} state=present
  with_items:
    - libvirt-daemon
    - qemu-kvm
    - libvirt-client-qemu
  ignore_errors: true

- name: Enable service
  ansible.builtin.service:
    name: libvirtd
    enabled: true
    state: started
