---
- name: VPAC[playbook]
  hosts: all
  user: root

  vars:
    console_keymap: en
    console_font: eurlatgr
    system_locale: en_US.UTF-8
    root_shell: /bin/bash
    domain: "{{ ansible_nodename.split('.')[1:] | join('.') }}"
    keys:
      - key: "{{ sshkey }}"

    system_timezone: Europe/Madrid
    ansible_connection: ssh
    ansible_ssh_user: root
    sshpassword: true

    gitrepos: []
    os: redhat

    timesync_ptp_domains:
      - number: 0
        interfaces: [enp9s0]
        transport: L2

    timesync_ntp_servers:
      - hostname: 192.168.200.77
        iburst: yes

    timesync_ntp_provider: chrony

    kernel_settings_sysctl:
      - name: vm.nr_hugepages
        value: 13312
      - name: kernel.nmi_watchdog
        value: 0
      - name: kernel.nmi_watchdog
        value: 0
      - name: kernel.sched_rt_runtime_us
        value: -1
    
    bootloader_settings:
      - kernel: ALL
        options:
          - name: quiet
            state: absent
          - name: idle
            value: poll
          - name: intel.max_cstate
            value: 0
          - name: intel_idle.max_cstate
            value: 0
          - name: processor.max_cstate
            value: 0
          - name: processor_idle.max_cstate
            value: 0
          - name: intel_pstate
            value: disable
          - name: rdt
            value: cmt,l3cat,l3cdp,mba
          - name: iomem
            value: relaxed
          - name: intel_iommu
            value: "on"
          - name: iommu
            value: pt
          - name: selinux
            value: 0
          - name: audit
            value: 0
    NON_RT_CORES_CAT: f
    NON_RT_CACHE_CAT: "0x1ff"
    tuned:
      rt_cores: 11-21
    RT_CACHE: "0x600"
    CPUMASK: "400"
    NICS: "enp6s0 enp9s0"

    profile: realtime-virtual-host

  roles:
    - linux-system-roles.bootloader
    - linux-system-roles.kernel_settings
    - linux-system-roles.timesync
    - linux-system-roles.tuned
    - vpac
    - network
    - ssc600
