galaxy_info:
  author: Costin Gament
  description: VM setup for SSC600
  license: GPL-2.0-or-later
  min_ansible_version: "2.9"
  platforms:
    - name: Linux
      versions:
        - all
  galaxy_tags: []
