---
- name: Write libvirt XML template
  ansible.builtin.template:
    src: libvirt-domain.xml.j2
    dest: "{{ ssc600_vm.path }}/{{ ssc600_vm.name }}.xml"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
