---
- name: Deploy SSC-600 VM startup script
  ansible.builtin.template:
    src: ssc600-setup.sh
    dest: /usr/sbin/ssc600-setup.sh
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  register: ssc600SetupScript

- name: Deploy SSC-600 VM startup service
  ansible.builtin.template:
    src: ssc600-startup.service.j2
    dest: /etc/systemd/system/ssc600-startup.service
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  register: ssc600StartupService

- name: Restart service
  ansible.builtin.systemd:
    name: ssc600-startup
    state: restarted
    enabled: true
    daemon_reload: true
  when: ssc600SetupScript.changed or ssc600StartupService.changed
