---
- name: Create bridge definition script for station
  ansible.builtin.copy:
    dest: /root/station-net.sh
    mode: 0755
    content: |
      #!/bin/bash

      nmcli connection down enp6s0

      nmcli connection add type bridge con-name station-bus ifname station-nic
      nmcli connection modify station-bus ipv4.method manual ipv4.addresses '192.168.2.105/24' ipv4.gateway '192.168.2.1'
      nmcli connection add type ethernet slave-type bridge con-name station-ext ifname enp6s0 master station-nic
      nmcli connection up station-bus
      nmcli connection up station-ext

- name: Execute bridge creation script for station
  ansible.builtin.shell: /root/station-net.sh
