---
  - name: Check if hosts are reachable
    ping:
    ignore_errors: yes
    register: ping_result

  - name: Fill variable with unreachable hosts
    set_fact:
      unreachable_hosts: "{{ ping_result | failed }}"
    when: ping_result is failed

  - name: Copy ssh keys
    shell: sshkeyscopy {{ rootpassword }} {{ item }}
    with_items: "{{ unreachable_hosts }}"
    delegate_to: localhost
    when: unreachable_hosts is defined
