---
- name: Check if hosts are reachable
  ansible.builtin.ping:
  ignore_errors: true
  register: ping_result

- name: Fill variable with unreachable hosts
  ansible.builtin.set_fact:
    unreachable_hosts: "{{ ping_result | failed }}"
  when: ping_result is failed

- name: Copy ssh keys
  ansible.builtin.shell: sshkeyscopy {{ rootpassword }} {{ item }}
  with_items: "{{ unreachable_hosts }}"
  delegate_to: localhost
  when: unreachable_hosts is defined
