---
- name: Remove rescue images
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop: "{{ query('fileglob', '/boot/*rescue*') | sort }}"

- name: Configure console
  ansible.builtin.copy:
    dest: /etc/vconsole.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    content: |
      KEYMAP="{{ console_keymap }}"
      FONT="{{ console_font }}"

- name: Configure locale
  ansible.builtin.copy:
    dest: /etc/locale.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    content: |
      LANG="{{ system_locale }}"

- name: Set timezone
  community.general.timezone:
    name: "{{ system_timezone }}"

- name: Remove unhelpful packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: absent
  with_items:
    - "abrt*"
    - language-pack-gnome-en
    - motd-news-config
    - command-not-found
    - update-notifier-common

- name: Install helpful packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - bash-completion
    - bc
    - sysstat
    - tmux
    - curl
    - ansible
    - cronie
    - util-linux
    - tuned
    - cmake
    - mc
    - pipx
    - nmap
    - tar
    - lz4
    - unzip
    - rsync
    - net-tools
    - joe
    - make
    - wget
    - git
    - jq
    - mlocate

- name: Enable helpful services
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    state: started
  with_items:
    - tuned
    - firewalld
    # - fstrim.timer

- name: Change root shell
  ansible.builtin.user:
    name: root
    shell: "{{ root_shell }}"
