---
- name: Install chrony package
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - chrony

- name: Enable chronyd services
  ansible.builtin.service:
    name: chronyd
    enabled: true
    state: started
