---
- name: Install logrotate package
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - logrotate

- name: Configure logrotate.conf
  ansible.builtin.lineinfile:
    dest: /etc/logrotate.conf
    create: true
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - {regexp: "^compress", line: "compress"}
    - {regexp: "^rotate.*", line: "rotate 14"}
    - {regexp: "^daily", line: "daily"}
    - {regexp: "^weekly.*", line: ""}
    - {regexp: "^dateext.*", line: ""}

- name: Limit Journal file size
  community.general.ini_file:
    path: /etc/systemd/journald.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    section: Journal
    option: SystemMaxUse
    value: 200M
