---
- name: Install helpful packages
  ansible.builtin.package: name={{ item }} state=present
  with_items:
    - firewalld
  ignore_errors: true
  when: sshpassword==True

- name: SSH Firewall rule
  ansible.posix.firewalld:
    service: ssh
    permanent: true
    state: enabled
    immediate: true
  ignore_errors: true
