---
- name: Install helpful packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - firewalld
  when: sshpassword==True

- name: SSH Firewall rule
  ansible.posix.firewalld:
    service: ssh
    permanent: true
    state: enabled
    immediate: true
