---
  - name: Increase user watches
    sysctl:
      name: fs.inotify.max_user_watches
      value: "1048576"
      state: present
      sysctl_set: yes
      reload: yes

  - name: Increase user watches
    sysctl:
      name: fs.inotify.max_user_instances
      value: "8192"
      state: present
      sysctl_set: yes
      reload: yes
